# Generated by Django 3.0.5 on 2020-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mer',
            field=models.BooleanField(default=False),
        ),
    ]
