# Generated by Django 3.0.5 on 2020-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order_mer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dely',
            field=models.BooleanField(default=False),
        ),
    ]
