# Generated by Django 3.0.5 on 2020-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_order_dely'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
