# Generated by Django 3.0.5 on 2020-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200422_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
